export const TODO_ADD_PENDING = 'TODO_ADD_PENDING';
export const TODO_ADD_SUCCESS = 'TODO_ADD_SUCCESS';
export const TODO_ADD_ERROR = 'TODO_ADD_ERROR';

export const TODO_DELETE_PENDING = 'TODO_DELETE_PENDING';
export const TODO_DELETE_SUCCESS = 'TODO_DELETE_SUCCESS';
export const TODO_DELETE_ERROR = 'TODO_DELETE_ERROR';

export const TODO_CHANGE_PENDING = 'TODO_CHANGE_PENDING';
export const TODO_CHANGE_SUCCESS = 'TODO_CHANGE_SUCCESS';
export const TODO_CHANGE_ERROR = 'TODO_CHANGE_ERROR';

export const TODO_DONE_PENDING = 'TODO_DONE_PENDING';
export const TODO_DONE_SUCCESS = 'TODO_DONE_SUCCESS';
export const TODO_DONE_ERROR = 'TODO_DONE_ERROR';

export const TODO_IMPORTANT_PENDING = 'TODO_IMPORTANT_PENDING';
export const TODO_IMPORTANT_SUCCESS = 'TODO_IMPORTANT_SUCCESS';
export const TODO_IMPORTANT_ERROR = 'TODO_IMPORTANT_ERROR';