export const TODO_ADD_PENDING = 'TODO_ADD_PENDING';
export const TODO_ADD_SUCCESS = 'TODO_ADD_SUCCESS';
export const TODO_ADD_ERROR = 'TODO_ADD_ERROR';

export const TODO_DELETE_PENDING = 'TODO_DELETE_PENDING';
export const TODO_DELETE_SUCCESS = 'TODO_DELETE_SUCCESS';
export const TODO_DELETE_ERROR = 'TODO_DELETE_ERROR';

export const TODO_TOGGLE_DONE_PENDING = 'TODO_TOGGLE_DONE_PENDING';
export const TODO_TOGGLE_DONE_SUCCESS = 'TODO_TOGGLE_DONE_SUCCESS';
export const TODO_TOGGLE_DONE_ERROR = 'TODO_TOGGLE_DONE_ERROR';

export const TODO_TOGGLE_IMPORTANT_PENDING = 'TODO_TOGGLE_IMPORTANT_PENDING';
export const TODO_TOGGLE_IMPORTANT_SUCCESS = 'TODO_TOGGLE_IMPORTANT_SUCCESS';
export const TODO_TOGGLE_IMPORTANT_ERROR = 'TODO_TOGGLE_IMPORTANT_ERROR';

export const TODO_TOGGLE_CHANGE_PENDING = 'TODO_TOGGLE_CHANGE_PENDING';
export const TODO_TOGGLE_CHANGE_SUCCESS = 'TODO_TOGGLE_CHANGE_SUCCESS';
export const TODO_TOGGLE_CHANGE_ERROR = 'TODO_TOGGLE_CHANGE_ERROR';

export const TODO_CHANGE_TITLE_PENDING = 'TODO_CHANGE_TITLE_PENDING';
export const TODO_CHANGE_TITLE_SUCCESS = 'TODO_CHANGE_TITLE_SUCCESS';
export const TODO_CHANGE_TITLE_ERROR = 'TODO_CHANGE_TITLE_ERROR';